github: [metadata]

title: Lost in the hex
email: scb5436@rit.edu
description: >- # this means to ignore newlines until "baseurl:"
  A small blog about computer security.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://onenutw0nder.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: oneNutW0nder
github_username:  scb5436@rit.edu

# Build settings
remote-theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

